blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Bugs5382/node-astronomy/discussions
    about: For general questions, ideas, and conversation, prefer Discussions.
