#!/usr/bin/env node
/**
 * Post-build step that wraps the tsdown bundle output with a thin shim that
 * silences `@observerly/astrometry`'s stale-IERS warning before the bundle
 * is evaluated.
 *
 * Why a post-build step (and not a top-of-source import in `src/index.ts`)?
 *  - In the CJS bundle, tsdown hoists every external `require(...)` to the
 *    top of the file. A `require()` for our suppressor would also be hoisted,
 *    and tsdown is free to reorder it relative to astrometry's. We can't
 *    rely on source order surviving the bundler.
 *  - In the ESM bundle, ECMAScript hoists all imports above any other
 *    statement at module scope. The patch must therefore live in a
 *    *separate* module that is imported before the bundle.
 *
 * The shim layout this script produces:
 *
 *   lib/{esm,cjs}/_suppress.{mjs,cjs}    -- patches console.warn
 *   lib/{esm,cjs}/_bundle.{mjs,cjs}      -- the actual tsdown output
 *   lib/{esm,cjs}/index.{mjs,cjs}        -- shim: import suppressor, then re-export bundle
 *   lib/esm/index.d.mts                  -- shim: re-export types from _bundle.d.mts
 *
 * The wrapper is hand-written (small) and the bundle is renamed in place.
 * Source maps and dts maps are renamed and their `sourceMappingURL` lines
 * fixed up to match.
 *
 * @since 0.2.0
 */

import { promises as fs } from "node:fs";
import path from "node:path";

const SUPPRESS_BODY = `// Auto-generated by scripts/inject-iers-suppressor.mjs.
// Filters one specific stale-leap-seconds warning emitted by
// @observerly/astrometry at module evaluation. The check is narrow on
// purpose — every other console.warn call is forwarded unchanged.
const _origWarn = console.warn;
console.warn = function () {
  var first = arguments[0];
  if (typeof first === "string" && first.indexOf("IERS leap seconds table is out of date") !== -1) {
    return;
  }
  _origWarn.apply(console, arguments);
};
`;

/**
 * Rename a file if it exists. Throws if neither source nor target exist.
 *
 * @param {string} from
 * @param {string} to
 * @returns {Promise<void>}
 */
async function renameIfExists(from, to) {
  try {
    await fs.rename(from, to);
  } catch (error) {
    if (error && error.code === "ENOENT") return;
    throw error;
  }
}

/**
 * Replace one literal text inside a file. No-op if the file does not exist
 * or does not contain the search string.
 *
 * @param {string} filePath
 * @param {string} search
 * @param {string} replace
 * @returns {Promise<void>}
 */
async function replaceInFile(filePath, search, replace) {
  let content;
  try {
    content = await fs.readFile(filePath, "utf8");
  } catch (error) {
    if (error && error.code === "ENOENT") return;
    throw error;
  }
  if (!content.includes(search)) return;
  await fs.writeFile(filePath, content.replace(search, replace));
}

/**
 * Wrap the CJS bundle. CJS does not hoist `require(...)`, so a synchronous
 * `require("./_suppress.cjs")` from the shim runs before the bundle's own
 * requires.
 */
async function wrapCjs(libraryDirectory) {
  const directory = path.join(libraryDirectory, "cjs");
  const indexCjs = path.join(directory, "index.cjs");
  const bundleCjs = path.join(directory, "_bundle.cjs");
  const indexCjsMap = path.join(directory, "index.cjs.map");
  const bundleCjsMap = path.join(directory, "_bundle.cjs.map");

  await renameIfExists(indexCjs, bundleCjs);
  await renameIfExists(indexCjsMap, bundleCjsMap);
  await replaceInFile(
    bundleCjs,
    "//# sourceMappingURL=index.cjs.map",
    "//# sourceMappingURL=_bundle.cjs.map",
  );

  await fs.writeFile(
    path.join(directory, "_suppress.cjs"),
    `"use strict";\n${SUPPRESS_BODY}`,
  );
  await fs.writeFile(
    indexCjs,
    `"use strict";\nrequire("./_suppress.cjs");\nmodule.exports = require("./_bundle.cjs");\n`,
  );
}

/**
 * Wrap the ESM bundle. ESM hoists imports, so the suppressor must live in
 * a separate module that the shim imports first. The bundle then loads via
 * `export *`, whose imports are evaluated in source order after _suppress.
 */
async function wrapEsm(libraryDirectory) {
  const directory = path.join(libraryDirectory, "esm");
  const indexMjs = path.join(directory, "index.mjs");
  const bundleMjs = path.join(directory, "_bundle.mjs");
  const indexMjsMap = path.join(directory, "index.mjs.map");
  const bundleMjsMap = path.join(directory, "_bundle.mjs.map");
  const indexDmts = path.join(directory, "index.d.mts");
  const bundleDmts = path.join(directory, "_bundle.d.mts");
  const indexDmtsMap = path.join(directory, "index.d.mts.map");
  const bundleDmtsMap = path.join(directory, "_bundle.d.mts.map");

  await renameIfExists(indexMjs, bundleMjs);
  await renameIfExists(indexMjsMap, bundleMjsMap);
  await renameIfExists(indexDmts, bundleDmts);
  await renameIfExists(indexDmtsMap, bundleDmtsMap);

  await replaceInFile(
    bundleMjs,
    "//# sourceMappingURL=index.mjs.map",
    "//# sourceMappingURL=_bundle.mjs.map",
  );
  await replaceInFile(
    bundleDmts,
    "//# sourceMappingURL=index.d.mts.map",
    "//# sourceMappingURL=_bundle.d.mts.map",
  );

  await fs.writeFile(path.join(directory, "_suppress.mjs"), SUPPRESS_BODY);
  await fs.writeFile(
    indexMjs,
    `import "./_suppress.mjs";\nexport * from "./_bundle.mjs";\n`,
  );
  await fs.writeFile(indexDmts, `export * from "./_bundle.mjs";\n`);
}

const libraryDirectory = path.resolve(process.cwd(), "lib");
await wrapCjs(libraryDirectory);
await wrapEsm(libraryDirectory);
console.log("[inject-iers-suppressor] wrapper shims written");
