name: Release Drafter

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  Update_Draft_Release:
    name: Release Drafter
    runs-on: ubuntu-latest

    steps:
      - name: Update Release Draft
        if: github.ref_name == 'main'
        uses: release-drafter/release-drafter@master
        with:
          commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}